### ISSUE TITLE
Duplication of  ConceptGraph node crashes Godot

### ISSUE THREAD

**Issue by wojtekpil** [HungryProton/concept_graph#1]
When I try to duplicate two trees in example scene Godot ram usage constantly goes up, until oom-killer kills it.

dmesg:

```
[20671.001410] Tasks state (memory values in pages):
[20671.001410] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
...
[20671.001600] [  25602]  1000 25602  3256586  1741972 22802432  1012200             0 Godot_v3.2-stab
...
[20671.001605] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=Godot_v3.2-stab,pid=25602,uid=1000
[20671.001628] Out of memory: Killed process 25602 (Godot_v3.2-stab) total-vm:13026344kB, anon-rss:6950188kB, file-rss:17392kB, shmem-rss:308kB
```

Steps to reproduce:
1. open example project
2. duplicate tree.
3. Select both tree nodes and try to duplicate

Another method:
1. open example project
2. duplicate tree.
3. Save project & restart

Godot logs:

```
OpenGL ES 3.0 Renderer: GeForce GTX 1660 Ti/PCIe/SSE2
 
Loaded Parent to node (parent_to_node.gd)
Loaded Box info (box_info.gd)
Loaded Jitter (jitter.gd)
Loaded Generic input (generic_input.gd)
Loaded Exclude from noise (exclude_from_noise.gd)
Loaded Simplex Noise (simplex_noise.gd)
Loaded Sample curve points (sample_points_constant.gd)
Loaded Smooth curve (smooth_curve.gd)
Loaded Tesselate curve (Curvature) (tessellate_curvature.gd)
Loaded To curve (points_to_curve.gd)
Loaded Tesselate curve (Exact) (tessellate_exact.gd)
Loaded Tesselate curve (Uniform) (tessellate_uniform.gd)
Loaded Midpoint displacement (midpoint_displacement.gd)
Loaded Expand curve (expand_curve.gd)
Loaded Make rectangle curve (create_square.gd)
Loaded Make multi line curves (create_line_multi.gd)
Loaded Make line curve (create_line.gd)
Loaded Make polygon curve (create_polygon.gd)
Loaded Curve Info (curve_info.gd)
Loaded Curve input (curve_input.gd)
Loaded Node Instancer (instancer.gd)
Loaded Make MultiMesh (make_multimesh.gd)
Loaded Palette (debug_palette.gd)
Loaded Offset (offset.gd)
Loaded Output (output.gd)
Loaded Divide scalars (divide_scalar.gd)
Loaded Mesh properties (edit_mesh_properties.gd)
Loaded Extrude polygon curve (extrude_straight.gd)
Loaded Extrude along curve (extrude_along_curve.gd)
Loaded Scale from noise (scale_from_noise.gd)
Loaded Boolean property (boolean.gd)
Loaded String property (string.gd)
Loaded Vector property (vector.gd)
Loaded Scalar property (scalar.gd)
Loaded Curve property (math_curve.gd)
Loaded Scalar (scalar.gd)
Loaded Create grid along curve (create_grid_along_curve.gd)
Loaded Spawn Duplicates (spawn_duplicates.gd)
Loaded Create point grid (create_grid.gd)
Loaded Points Array (points_array.gd)
Loaded Break Vector (break_vector.gd)
Loaded Exclude from curves (exclude_from_curve.gd)
Loaded Box input (box_input.gd)
Loaded Make vector (make_vector.gd)
Loaded Rotate (rotate.gd)
ERROR: get_tree: Condition "!data.tree" is true. Returned: __null
   At: scene/main/node.h:281.
ERROR: get_tree: Condition "!data.tree" is true. Returned: __null
   At: scene/main/node.h:281.
ERROR: get_tree: Condition "!data.tree" is true. Returned: __null
   At: scene/main/node.h:281.
ERROR: get_tree: Condition "!data.tree" is true. Returned: __null
   At: scene/main/node.h:281.
ERROR: get_tree: Condition "!data.tree" is true. Returned: __null
   At: scene/main/node.h:281.
Loaded Parent to node (parent_to_node.gd)
Loaded Box info (box_info.gd)
Loaded Jitter (jitter.gd)
Loaded Generic input (generic_input.gd)
Loaded Exclude from noise (exclude_from_noise.gd)
Loaded Simplex Noise (simplex_noise.gd)
Loaded Sample curve points (sample_points_constant.gd)
Loaded Smooth curve (smooth_curve.gd)
Loaded Tesselate curve (Curvature) (tessellate_curvature.gd)
Loaded To curve (points_to_curve.gd)
Loaded Tesselate curve (Exact) (tessellate_exact.gd)
Loaded Tesselate curve (Uniform) (tessellate_uniform.gd)
Loaded Midpoint displacement (midpoint_displacement.gd)
Loaded Expand curve (expand_curve.gd)
Loaded Make rectangle curve (create_square.gd)
Loaded Make multi line curves (create_line_multi.gd)
Loaded Make line curve (create_line.gd)
Loaded Make polygon curve (create_polygon.gd)
Loaded Curve Info (curve_info.gd)
Loaded Curve input (curve_input.gd)
Loaded Node Instancer (instancer.gd)
Loaded Make MultiMesh (make_multimesh.gd)
Loaded Palette (debug_palette.gd)
Loaded Offset (offset.gd)
Loaded Output (output.gd)
Loaded Divide scalars (divide_scalar.gd)
Loaded Mesh properties (edit_mesh_properties.gd)
Loaded Extrude polygon curve (extrude_straight.gd)
Loaded Extrude along curve (extrude_along_curve.gd)
Loaded Scale from noise (scale_from_noise.gd)
Loaded Boolean property (boolean.gd)
Loaded String property (string.gd)
Loaded Vector property (vector.gd)
Loaded Scalar property (scalar.gd)
Loaded Curve property (math_curve.gd)
Loaded Scalar (scalar.gd)
Loaded Create grid along curve (create_grid_along_curve.gd)
Loaded Spawn Duplicates (spawn_duplicates.gd)
Loaded Create point grid (create_grid.gd)
Loaded Points Array (points_array.gd)
Loaded Break Vector (break_vector.gd)
Loaded Exclude from curves (exclude_from_curve.gd)
Loaded Box input (box_input.gd)
Loaded Make vector (make_vector.gd)
Loaded Rotate (rotate.gd)
Memory MB : 99
ERROR: remove_child: Parameter "p_child" is null.
   At: scene/main/node.cpp:1232.
ERROR: add_child: Parameter "p_child" is null.
   At: scene/main/node.cpp:1174.
Memory MB : 110
ERROR: remove_child: Parameter "p_child" is null.
   At: scene/main/node.cpp:1232.
ERROR: add_child: Parameter "p_child" is null.
   At: scene/main/node.cpp:1174.
Memory MB : 115
ERROR: remove_child: Parameter "p_child" is null.
   At: scene/main/node.cpp:1232.
ERROR: add_child: Parameter "p_child" is null.
   At: scene/main/node.cpp:1174.
Memory MB : 120
ERROR: remove_child: Parameter "p_child" is null.
   At: scene/main/node.cpp:1232.
ERROR: add_child: Parameter "p_child" is null.
   At: scene/main/node.cpp:1174.
Memory MB : 125
Failed method: VScrollBar:_update_minimum_size target ID: 76936
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
...
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback
```

**Comment by HungryProton** [comment]
Should be fixed by ebb7a3aaa06864852313a2fff155248dee9d83bb
I can't reproduce the error at my side, let me know if it works for you

**Comment by wojtekpil** [comment]
I tried with  [ebb7a3a](https://github.com/HungryProton/concept_graph/commit/ebb7a3aaa06864852313a2fff155248dee9d83bb). Problem still persists. Here is a video [link](https://streamable.com/u71dbi) showing steps to reproduce.

**Comment by HungryProton** [comment]
So I do have the same issue, but I'm really not sure what's going on there. Other issues that mention this error : "Object was deleted while awaiting a callback" seems to be related either to the inspector or to node trees too complex. 

If I duplicate the grass instead of the tree, the issue doesn't happen, so It's probably related to the many mesh instances created in a single frame. My guess is : this will go away as soon as I figure out how to thread the generation process and defer the multiple add_child calls.

**Comment by HungryProton** [comment]
**Short update :** Temporary workaround for this issue is to increase 'message_queue_size_kb' in the project settings. The larger the graph the larger the queue size should be. 

**Long update :**
Increasing the message queue size is not a viable fix.
It's possible to duplicate 2 trees at once after removing 5 - 10 nodes from the graph so this issue is directly related to the graph size.

If the message queue is full, that's probably because :
- There's too many nodes being created at once
- Too many nodes being deleted at once
- Other things I'm not aware of

So I'm moving everything to an async model (that was planned anyway for performance reasons).
This means each node will run their logic in a thread, so the editor wont freeze while it's processing and will spread the generation over multiple frames instead of a single one, making the call stack for each frame much smaller. The new "garbage collector" is causing issues with too many queue_free too so this is going to be replaced too.

Making all of this work requires a thread pool, a thread-safe node pool and a few changes in how some functions are called.
