### ISSUE TITLE
Merge meshes - multiple inputs and single surface checkbox

### ISSUE THREAD

**Issue by BryceBubbles** [HungryProton/concept_graph#35]
I've only just started playing with the examples, so I might have missed something that gets the same result I'm about to outline? Anyway...

It would add a lot of flexibility if the `Merge meshes` node would allow for multiple inputs. 
As well as having an `As single surface` checkbox that merges everything into a single surface on the mesh, in order to minimise draw calls (I'm guessing this is much more complex than just merging surfaces - which is something I've done in gdscript before).

So for the simple tree example:
1. The trunk, branches, and sub-branches would all link their `Extrude along curve` outputs into `Merge meshes` with `As single surface` checked. 
2. The leaves would do the same on their own `Merge meshes` node. 
3. Then both of their outputs would go into another `Merge meshes` node without `As single surface` checked.

And now you have a single tree mesh with only 2 surfaces, which could be piped into a `MultiMesh`, or even just saved to disk via the inspector.

**Comment by HungryProton** [comment]
That's on my to-do list, Merge meshes should have a merge surface option and a dynamic slot system like the one in parent to node.

**Comment by BryceBubbles** [comment]
I got this working, including merging surfaces, and I could setup a pull request, but...

I copied the dynamic slot system in parent_to_node and:
1. The latest 0.3 release has a bug with the remove button leaving an unnamed input behind.
2. I see that you want to move the dynamic slot system into ConceptNode.

So I'm not sure if you'll want to add my changes yet?

**Comment by HungryProton** [comment]
Right I forgot about this, the whole default gui code is a mess... I'll move this part in the base class as soon as I can since there a few nodes that could benefit from this.

**Comment by HungryProton** [comment]
I moved the dynamic input system in the base class in c79993de9861813e106e51dbd09e87248272b22f

Merge Meshes and Parent to Node both use this now

**Comment by BryceBubbles** [comment]
Awesome!

I've just had a quick look and `_inputs.size()` in `get_input_count()` seems to include the dynamic inputs already, so it's returning a value with the dynamic inputs added twice:
https://github.com/HungryProton/concept_graph/blob/ead7fac1f88ddea6d69633b02507f0b1fe471dbc/src/core/concept_node.gd#L123-L126

Also if I replace `Parent to node` with `Merge meshes` in the `simple_tree` example, the trunk gets skipped as it's a single MeshInstance.
https://github.com/HungryProton/concept_graph/blob/ead7fac1f88ddea6d69633b02507f0b1fe471dbc/src/nodes/meshes/merge_meshes.gd#L27

Note: I'm not very experienced with contributing on Github, so can you let me know if this type of reply is ok, or could I have done this in a more helpful way?

**Comment by BryceBubbles** [comment]
Also, with these dynamic inputs...

In order to add separate inputs that stay after the dynamic inputs (like a Merge Surface checkbox), we'd have to shift it's id every time a dynamic input is added or removed right? I know the simple solution is to put all other inputs first, but that might not always be ideal.

I see that you want to decouple the input id from the visual position per #11, but even with that in place, we'd still have to shift the visual position around in the above situation ay?

It makes me wonder if the dynamic inputs should be implemented as an ARRAY input type which you access with a single input id/position? I'm not sure how feasible that is though, as a lot of that base class stuff is over my head at the moment.

**Comment by HungryProton** [comment]
Good catch with the get_input_counts

For merge meshes no line 27, it should be an issue because get_input always return an array, no matter how many items it have, even if there's a single one so the issue probably comes from something else.

Changing the id dynamically sounds like a lot of trouble. It's not an issue to put every static slot at the beginning. But I guess it could be possible to abstract that into a single slot to allow multiple types of dynamic inputs on the same node. I'll see what I can do before the next release as this breaks backward compatibility with previous templates.

**Comment by HungryProton** [comment]
Oh I see what you mean, it's the size check that should be <= 0 instead of one.
Fixed in 0034ccdd6fea8740ecf7950a0f30c18cc6917ace

**Comment by HungryProton** [comment]
Alright, this is broken again and I don't even know why. I'm giving up on this dynamic system and moving with your suggestion of allowing multiple connections to the same input.

Inputs that allow this will have the same color but a different shape (probably square) to make it clearer they're different.

**Comment by BryceBubbles** [comment]
It sucks when when that happens.

I think what I had in mind was still having the dynamic input points to connect to, but the implementation was an Array node type on the code side.

A single input might be simpler and more robust, but it makes removing connections a bit trickier.

The best option I can think of would be for each click on the input to pick up the next connection, based on the order they were added? Is that what you're thinking?

**Comment by HungryProton** [comment]
I'm thinking of using a single slot for multiple connections even if that means connections are harder to remove. Maybe adding a shortcut to remove a connection when hovering it?

**Comment by BryceBubbles** [comment]
That could be helpful too.
Iterating the connection selected on each click could be quite usable though, and might be easier to implement?

**Comment by HungryProton** [comment]
That could work too, thanks for the suggestion!

**Comment by HungryProton** [comment]
Not sure if these are visible enough but inputs that accepts multiple connections now have a square icon.

![image](https://user-images.githubusercontent.com/52043844/83165365-b3b74280-a10d-11ea-8cfe-08b32ef088bc.png) 7a2a1e904e92a99c92be76b9a874e87fbb55171a


Default behavior for GraphEdits with multiple connections is clicking the input slot will delete the first connection in order they were made. Clicking and holding will detach the connection and once it's reconnected, clicking and holding will select the next one. It's not ideal and I'm not sure the GraphEdit API actually expose enough things to change this behavior but I guess it's fine for now.
