### ISSUE TITLE
simple_tree example scene is not loading after 0.3 version

### ISSUE THREAD

**Issue by IvailoBurov** [HungryProton/concept_graph#82]
simple_tree_forest is not loading too.

**Comment by HungryProton** [comment]
It should be fixed in the latest commit ea238351bf3c1f550f42aa30067bd3e573bfded9 (on the master branch)
That scene takes forever to load though, I think it's because of the shader compilation.

**Comment by IvailoBurov** [comment]
Still get errors. Here is a part of console messages:

Godot Engine v3.2.2.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: Radeon RX 560 Series

ERROR: Resource file not found: res://materials/wood/t_tree_bark_1.png.
   At: core/io/resource_loader.cpp:282
ERROR: Resource file not found: res://materials/wood/t_tree_bark_1.png.
   At: core/io/resource_loader.cpp:282
WARNING: _parse_ext_resource: Couldn't load external resource: res://materials/wood/t_tree_bark_1.png
     At: scene/resources/resource_format_text.cpp:175
ERROR: get_tree: Condition "!data.tree" is true. Returned: __null
   At: scene/main/node.h:281
SCRIPT ERROR: _set_vector_value: Invalid call. Nonexistent function 'length' in base 'bool'.
          At: res://addons/concept_graph/src/nodes/generators/meshes/3d/extrude_along_curve.gd:803
SCRIPT ERROR: _set_vector_value: Invalid call. Nonexistent function 'length' in base 'bool'.
          At: res://addons/concept_graph/src/nodes/generators/meshes/3d/extrude_along_curve.gd:803
Saving template res://addons/concept_graph/examples/templates/palm_tree.cgraph
ERROR: get_tree: Condition "!data.tree" is true. Returned: __null
   At: scene/main/node.h:281
ERROR: get_tree: Condition "!data.tree" is true. Returned: __null
   At: scene/main/node.h:281
Failed method: EditorSpinSlider:_update_callback target ID: 77658
Object was deleted while awaiting a callback
Object was deleted while awaiting a callback

This line lops forever:
Object was deleted while awaiting a callback

**Comment by wojtekpil** [comment]
Your problem is described on the wiki:
"If you're facing a bug that freezes the whole editor, with a message like" Object deleted while awaiting callback "or similar looping in the console, go to your project settings, under Memory -> Limits, increase the Message queue max size . "
It should fix it.

**Comment by IvailoBurov** [comment]
Thanks,
Increasing memory limit to 4096 fix this issue.
